package com.seckillproject.DAO;

import com.seckillproject.dataObject.ItemDAO;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface ItemDAOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item
     *
     * @mbg.generated Sat Mar 26 21:03:35 EDT 2022
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item
     *
     * @mbg.generated Sat Mar 26 21:03:35 EDT 2022
     */
    int insert(ItemDAO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item
     *
     * @mbg.generated Sat Mar 26 21:03:35 EDT 2022
     */
    int insertSelective(ItemDAO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item
     *
     * @mbg.generated Sat Mar 26 21:03:35 EDT 2022
     */
    ItemDAO selectByPrimaryKey(Integer id);

    List<ItemDAO> listItem();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item
     *
     * @mbg.generated Sat Mar 26 21:03:35 EDT 2022
     */
    int updateByPrimaryKeySelective(ItemDAO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item
     *
     * @mbg.generated Sat Mar 26 21:03:35 EDT 2022
     */
    int updateByPrimaryKey(ItemDAO record);

    int increaseSales(@Param("id") Integer itemId, @Param("amount") Integer amount);
}