package com.seckillproject.DAO;

import com.seckillproject.dataObject.OrderDAO;

public interface OrderDAOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_info
     *
     * @mbg.generated Sun Mar 27 15:02:01 EDT 2022
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_info
     *
     * @mbg.generated Sun Mar 27 15:02:01 EDT 2022
     */
    int insert(OrderDAO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_info
     *
     * @mbg.generated Sun Mar 27 15:02:01 EDT 2022
     */
    int insertSelective(OrderDAO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_info
     *
     * @mbg.generated Sun Mar 27 15:02:01 EDT 2022
     */
    OrderDAO selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_info
     *
     * @mbg.generated Sun Mar 27 15:02:01 EDT 2022
     */
    int updateByPrimaryKeySelective(OrderDAO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_info
     *
     * @mbg.generated Sun Mar 27 15:02:01 EDT 2022
     */
    int updateByPrimaryKey(OrderDAO record);
}