package com.seckillproject.DAO;

import com.seckillproject.dataObject.PromoDAO;

public interface PromoDAOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table promo
     *
     * @mbg.generated Sun Mar 27 17:31:15 EDT 2022
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table promo
     *
     * @mbg.generated Sun Mar 27 17:31:15 EDT 2022
     */
    int insert(PromoDAO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table promo
     *
     * @mbg.generated Sun Mar 27 17:31:15 EDT 2022
     */
    int insertSelective(PromoDAO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table promo
     *
     * @mbg.generated Sun Mar 27 17:31:15 EDT 2022
     */
    PromoDAO selectByPrimaryKey(Integer id);

    PromoDAO selectByItemId(Integer itemId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table promo
     *
     * @mbg.generated Sun Mar 27 17:31:15 EDT 2022
     */
    int updateByPrimaryKeySelective(PromoDAO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table promo
     *
     * @mbg.generated Sun Mar 27 17:31:15 EDT 2022
     */
    int updateByPrimaryKey(PromoDAO record);
}