package com.seckillproject.DAO;

import com.seckillproject.dataObject.SequenceDAO;

public interface SequenceDAOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sequence_info
     *
     * @mbg.generated Sun Mar 27 15:40:13 EDT 2022
     */
    int deleteByPrimaryKey(String name);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sequence_info
     *
     * @mbg.generated Sun Mar 27 15:40:13 EDT 2022
     */
    int insert(SequenceDAO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sequence_info
     *
     * @mbg.generated Sun Mar 27 15:40:13 EDT 2022
     */
    int insertSelective(SequenceDAO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sequence_info
     *
     * @mbg.generated Sun Mar 27 15:40:13 EDT 2022
     */
    SequenceDAO selectByPrimaryKey(String name);

    SequenceDAO selectSequenceByName(String name);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sequence_info
     *
     * @mbg.generated Sun Mar 27 15:40:13 EDT 2022
     */
    int updateByPrimaryKeySelective(SequenceDAO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sequence_info
     *
     * @mbg.generated Sun Mar 27 15:40:13 EDT 2022
     */
    int updateByPrimaryKey(SequenceDAO record);
}