package com.seckillproject.DAO;

import com.seckillproject.dataObject.UserPasswordDAO;

public interface UserPasswordDAOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_password
     *
     * @mbg.generated Fri Mar 25 17:54:01 EDT 2022
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_password
     *
     * @mbg.generated Fri Mar 25 17:54:01 EDT 2022
     */
    int insert(UserPasswordDAO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_password
     *
     * @mbg.generated Fri Mar 25 17:54:01 EDT 2022
     */
    int insertSelective(UserPasswordDAO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_password
     *
     * @mbg.generated Fri Mar 25 17:54:01 EDT 2022
     */
    UserPasswordDAO selectByPrimaryKey(Integer id);

    UserPasswordDAO selectByUserId(Integer userId);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_password
     *
     * @mbg.generated Fri Mar 25 17:54:01 EDT 2022
     */
    int updateByPrimaryKeySelective(UserPasswordDAO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_password
     *
     * @mbg.generated Fri Mar 25 17:54:01 EDT 2022
     */
    int updateByPrimaryKey(UserPasswordDAO record);
}